
DROP TABLE IF EXISTS users;
CREATE TABLE users (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       first_name VARCHAR(100),
                       last_name VARCHAR(100),
                       user_name VARCHAR(100) UNIQUE,
                       password VARCHAR(100),
                       email VARCHAR(100),
                       phone VARCHAR(20),
                       role VARCHAR(50)
);
